/* Isolated link and promotion-motion checks: never opens tester shopping windows. */
(async()=>{
const wait=ms=>new Promise(r=>setTimeout(r,ms)),report={tests:[],errors:[],motion:[]};
addEventListener('error',e=>report.errors.push(e.message));
const check=(name,ok,detail)=>report.tests.push({name,pass:!!ok,detail});
await wait(3700);VCApp.testLayout(402,874);const L=VCApp._L;
const state=p=>new Promise(r=>L.setState(p,r));
await state({tier:'m12',splash:false,loading:false,iam:'',modal:'',tab:'home',history:[]});await wait(400);
const anchors=Array.from(document.querySelectorAll('[data-banners] a'));
check('iPhone Duo is first and goes directly to matching product',anchors[0].href===VCShopLinks.duo);
check('New campaigns have separate product destinations',anchors[1].href===VCShopLinks.instax&&anchors[2].href===VCShopLinks.huawei);
check('F1 and outdated hero artwork excluded',anchors.length===3&&!anchors.some(a=>/acer|brother|f1|pitstop/i.test(a.outerHTML)));
await Promise.all(anchors.map(a=>a.querySelector('img').decode().catch(()=>{})));
check('All three hero images are square',anchors.every(a=>{const i=a.querySelector('img');return i.naturalWidth===i.naturalHeight&&i.naturalWidth>0;}));
let renders=0;const render=L.renderVals.bind(L);L.renderVals=function(){renders++;return render();};
const row=document.querySelector('[data-banners]');row.scrollLeft=row.clientWidth;
for(let i=0;i<30;i++)row.dispatchEvent(new Event('scroll'));await wait(120);
check('Banner scroll never renders the page',renders===0,renders);
check('Banner dot tracks second page',L._bannerIndex===1,L._bannerIndex);
check('Banner keeps browser-native horizontal snap',getComputedStyle(row).scrollSnapType==='x mandatory');
let captured=[];const open=VCApp.openShop;VCApp.openShop=u=>captured.push(u);
let vals=render();vals.dealItems.forEach(d=>d.go());check('All six product taps use distinct matching destinations',captured.length===6&&new Set(captured).size===6&&captured.every((u,i)=>u===VCShopLinks.laptops[i]));
captured=[];vals.dealSeeAll();check('See all opens laptop collection',captured[0]===VCShopLinks.laptop1010);
captured=[];vals.homePromos.slice(1).forEach(p=>p.open());check('Other deal tiles have matching campaign destinations',captured.join('|')===[VCShopLinks.polaroid,VCShopLinks.valore,VCShopLinks.mario].join('|'));
captured=[];L.toastMsg('Your receipt is ready on online.challenger.sg');await wait(300);check('Informational text never opens the homepage',captured.length===0);
L.go('deal');await wait(400);const s14=document.querySelector('img[src="assets/zenbook.png"]');check('S14 image has white background',s14&&getComputedStyle(s14).backgroundColor==='rgb(255, 255, 255)');
L.back();await wait(380);await state({iam:'duo'});await wait(20);
const scrim=document.querySelector('[data-fx="scrim"]'),card=scrim?.firstElementChild;
check('iPhone pop-up opens',!!card);
const frames=card?.getAnimations().flatMap(a=>a.effect.getKeyframes())||[];
check('Pop-up moves without scaling its artwork or text',frames.some(f=>f.transform?.includes('translate3d'))&&frames.every(f=>!f.transform?.includes('scale')));
check('No full-screen opacity group during pop-up motion',!scrim?.getAnimations().some(a=>a.effect.getKeyframes().some(f=>'opacity'in f)));
const samples=[];let last=performance.now();await new Promise(resolve=>{function tick(now){samples.push(now-last);last=now;if(samples.length<35)requestAnimationFrame(tick);else resolve();}requestAnimationFrame(tick);});
report.motion.push({scope:'Desktop preview only; not physical iPhone frame-rate certification',meanMs:samples.reduce((a,b)=>a+b,0)/samples.length,maxMs:Math.max(...samples)});
await wait(280);check('Temporary promotion layer hint clears',card.style.willChange==='');
render().closeIam();await wait(230);check('Promotion closes without stranded overlay',!document.querySelector('[role="dialog"][aria-label="iPhone Duo is here"]'));
VCApp.openShop=open;check('No runtime errors',report.errors.length===0,report.errors);
report.passed=report.tests.filter(t=>t.pass).length;report.total=report.tests.length;
const output=document.createElement('pre');output.id='qa-report';output.textContent=JSON.stringify(report,null,2);document.body.append(output);
})();
